import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={'p-32'}>
      <Head>
        <title>Angela PP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-center w-2/'>
        <p className='text-2xl'>Hola Soy Angela</p>
        <p className='text-sm'>Hola Soy Angela</p>
        <button className='rounded-full py-2 px-5 bg-orange-500 hover:bg-red-300 hover:p-10 text-orange-900'>Hola</button>
      </div>
    </div>

  )
}
